version: '3'
volumes:
  database:
services:
  database:
    image: postgres:11.7-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nfl_rush_dev
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
